kind: pipeline
type: docker
name: publish

trigger:
  event: [ push, tag ]
  ref: [ "refs/heads/master", "refs/tags/**" ]

steps:
  - name: restore-gradle-cache
    image: meltwater/drone-cache
    pull: if-not-exists
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: oss_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: oss_key_secret
    settings:
      bucket: teacon-drone-cache
      region: cn-hangzhou
      endpoint: teacon-drone-cache.oss-accelerate.aliyuncs.com
      cache_key: "{{ .Commit.Branch }}-{{ checksum \"src/resources/META-INF/accesstransformer.cfg\" }}-gradle-cache-nightly"
      restore: true
      mount:
        - /root/.gradle
    volumes:
      - name: gradle-cache
        path: /root/.gradle

  - name: build-nightly
    image: azul/zulu-openjdk-alpine:17
    commands:
      - ./gradlew build --no-daemon
    volumes:
      - name: gradle-cache
        path: /root/.gradle
    depends_on:
      - restore-gradle-cache
    when:
      ref:
        exclude: [ "refs/tags/**" ]

  - name: publish
    image: azul/zulu-openjdk-alpine:17
    environment:
      GITEA_TOKEN:
        from_secret: gitea_token
      TEACON_ARCHIVE_ACCESS_KEY:
        from_secret: archive_access_key
      TEACON_ARCHIVE_ACCESS_SECRET:
        from_secret: archive_access_secret
    commands:
      - ./gradlew -Dorg.gradle.s3.endpoint=https://teacon2021.oss-cn-shanghai.aliyuncs.com
        publishReleasePublicationToTeaConOSSRepository
        publishReleasePublicationToTeaConGiteaRepository  --no-daemon
    volumes:
      - name: gradle-cache
        path: /root/.gradle
    depends_on:
      - restore-gradle-cache
    when:
      ref:
        - refs/tags/**

  - name: rebuild-gradle-cache
    image: meltwater/drone-cache
    pull: if-not-exists
    environment:
      AWS_ACCESS_KEY_ID:
        from_secret: oss_key_id
      AWS_SECRET_ACCESS_KEY:
        from_secret: oss_key_secret
    settings:
      bucket: teacon-drone-cache
      region: cn-hangzhou
      endpoint: teacon-drone-cache.oss-accelerate.aliyuncs.com
      cache_key: "{{ .Commit.Branch }}-{{ checksum \"src/resources/META-INF/accesstransformer.cfg\" }}-gradle-cache-nightly"
      rebuild: true
      override: false
      mount:
        - /root/.gradle
    volumes:
      - name: gradle-cache
        path: /root/.gradle
    depends_on:
      - build-nightly
      - publish

volumes:
  - name: gradle-cache
    temp: { }

node:
  mainland: "false"
